config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => {
    :verify_authy => "/verify_token",
    :enable_authy => "/enable_two_factor",
    :verify_authy_installation => "/verify_installation",
    :authy_onetouch_status => "/onetouch_status"
  }

  get 'welcome/index'

  resources :notes do
    member do
      patch :complete
    end
  end

  authenticated :user do
    root 'notes#index', as: 'authenticated_root'
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  has_rich_text :content

  before_validation :set_title_using_content, if: :title_missing?

  validates :title, length: { maximum: 30 }, allow_blank: true
  validate :title_or_content_present
  validate :content_length, unless: :content_missing?

  scope :unfinished, -> { where(complete: false) }

  CELEBRATIONS = %w[Yas Congratulations Congrats Nice Hooray Applause Winning Baller
                    Awesome Stoked Amazing Excellent Exceptional].freeze

  private

    def set_title_using_content
      self.title = content&.to_plain_text[0...30]
    end

    def content_missing?
      content.blank?
    end

    def title_missing?
      title.blank?
    end

    def title_or_content_present
      return true unless title_missing? && content_missing?

      errors.add(:base, 'Must have a title or content to create note')
    end

    def content_length
      return true unless self.content.body.to_plain_text.length >= 1000

      errors.add(:content, 'is too long (maximum is 1000 characters)')
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :authy_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: %i[show edit update destroy complete]
  before_action :authenticate_user!

  def index
    @notes = policy_scope(Note).unfinished.order(updated_at: :desc).with_rich_text_content_and_embeds
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to @note
      flash[:notice] = 'Note successfully created!'
    else
      flash[:alert] = "Unable to create note: #{@note.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
      flash[:notice] = 'Note successfully updated!'
    else
      flash[:alert] = "Unable to update note: #{@note.errors.full_messages.join(', ')}"
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path, alert: 'Note successfully deleted!'
  end

  def complete
    @note.update(complete: true)
    respond_to do |format|
      format.html { redirect_to notes_url, alert: 'Note successfully archived!' }
      format.js { flash.now[:notice] = 'Note successfully archived!' }
    end
  end

  private

    def find_note
      @note = authorize(Note.find(params[:id]))
    end

    def note_params
      params.require(:note).permit(:title, :content, :task)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_svg(path)
    File.open("app/assets/images/#{path}", 'rb') do |file|
      raw file.read
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def show_random_button(notes)
    notes.select(&:task).size >= 5
  end

  def random_task(notes)
    notes.unfinished.where(task: true).order(:created_at).limit(5).sample
  end

  def grab_giphy(celebrations)
    url="http://api.giphy.com/v1/gifs/search?q=#{celebrations}&api_key=#{ENV["GIPHY_API_KEY"]}&limit=1"
    resp = Net::HTTP.get_response(URI.parse(url))
    buffer = resp.body
    result = JSON.parse(buffer)
    source = result.fetch('data')[0]['embed_url']
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_errors.html.erb
<div class="content">
  <% if flash[:notice] %>
    <div class="flash notice">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="flash alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <%= link_to image_tag('logo.jpg', size: 120), root_path %>

  <% if user_signed_in? %>
    <div class="form-group float-right">
      <%= link_to 'New note', new_note_path, class: 'mt-3 btn btn-primary' %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'mt-3 btn btn-primary' %>

      <% unless current_user.authy_enabled %>
        <div class="form-group mt-2">
          <%= link_to user_enable_authy_path, data: { turbolinks: false }, class: 'form-control btn btn-outline-secondary', style: 'color: silver' do %>
            <span>Tinfoil hat mode: <%= image_tag('cone.svg')%></span>
          <% end %>
        </div>
      <% end %>

    </div>

  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary float-right' %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NucleusNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://www.authy.com/form.authy.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.authy.com/form.authy.min.js" %>

  </head>

  <body>
    <div style="min-height: 120px">
      <% if user_signed_in? || controller_name == 'welcome' %>
        <%= render 'layouts/navbar' %>
      <% end %>
    </div>

    <div id="flash">
      <%= render partial: "layouts/errors" %>
    </div>

    <br>

    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<div class="devise-form">
  <div class="card p-5 mx-auto text-center">
    <%= form_with model: @note, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, autofocus: true, autocomplete: 'off', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content %><br>
        <%= f.rich_text_area :content, class: 'text-left' %>
      </div>

      <div class="form-group">
        <%= f.label 'Is this a task?' %>
        <%= f.check_box :task %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>

      <% unless @note.new_record? %>
        <%= link_to 'Cancel', @note, class: 'btn btn-outline-secondary' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/notes/_note.html.erb
<div id="<%= dom_id(note) %>" class="card p-2 m-2" style="min-width:25%;">
  <div id="note_#{note.id}" style="position: absolute; top:1.5em; right:0em; left:auto;" data-toggle="modal" data-target="#myModal">
    <%= link_to complete_note_path(note), method: :patch, remote: true do %>
      <div class="check-or-not" data-toggle="tooltip" data-placement="top" title="Archive this note"></div>
    <% end %>
  </div>
  <h5 class="card-body"><%= note.title %></h5>
  <p class="card-text"><%= note.content %></p>
  <p class="card-text">
    <small class="text-muted"><%= "Last updated #{time_ago_in_words(note.updated_at)} ago" %></small>
  </p>
  <%= link_to 'View details', note, class: "btn btn-primary" %>
</div>

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <iframe src="<%= grab_giphy(Note::CELEBRATIONS.sample) %>" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/notes/complete.js.erb
$('#note_<%= @note.id %>').fadeTo(1000, 0.01, function(){
  $(this).remove();
});
$("#flash").html('<%= j render partial: "layouts/errors" %>');

app/views/notes/edit.html.erb
<div class="text-center mx-auto">
  <h1>Edit note</h1>

  <%= render 'form', note: @note %>
</div>

app/views/notes/index.html.erb
<center>
  <h1>My Envelope</h1><br>

  <% if show_random_button(@notes) %>
    <div class="mb-4">
      <h4>Which task should I start on next?</h4>
      <%= link_to 'Randomize', note_path(random_task(@notes)), class: 'btn btn-secondary' %>
    </div>
  <% end %>

  <% unless @notes.blank? %>
    <div class="card-deck mx-auto">
      <%= render partial: 'note', collection: @notes %>
    </div>
  <% else %>
    <p>Looks like you don't have any notes. Create one using the button below!</p>
    <%= link_to 'New note', new_note_path, class: 'btn btn-primary' %>
  <% end %>
</center>

app/views/notes/new.html.erb
<div class="text-center mx-auto">
  <h1>New note</h1>

  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<h1 class="text-center">Your note</h1>
<div class="devise-form mb-2">
  <div class="card p-5 mx-auto text-center">
    <div id="note_#{@note.id}" style="position: absolute; top:1.5em; right:0em; left:auto;">
      <%= link_to complete_note_path(@note), method: :patch, local: true do %>
        <div class="check-or-not" data-toggle="tooltip" title="Archive this note"></div>
      <% end %>
    </div>
    <h2><%= @note.title %></h2>
    <p><%= @note.content %></p>

    <div class="form-group">
      <%= link_to 'Edit', edit_note_path(@note), class: 'btn btn-primary' %><br>
    </div>
    <div class="form-group">
    <%= link_to 'Delete', note_path(@note), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-outline-secondary' %>
    </div>
    <div>
      <%= mail_to('', 'Email contents of note', subject: @note.title, body: @note.content.body.to_plain_text, reply_to: current_user.email, class: 'btn btn-secondary') %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Keep your head in the clouds</h1>
  <h1>by storing your next big idea there. </h1>
  <p class="lead">Access your notes whenever, wherever, and on whatever device you're closest to.</p>
  <hr class="my-4" style="width: 50%">
  <p>With your help, we can make sticky notes a relic of the past.</p>
  <%= link_to 'Sign up for free', new_user_registration_path, class: "btn btn-primary" %>
</div>